Add Sea-Surface Salinity index
MarcoLandtHayen/climate_index_collection pull request #69
Opened 2022-08-11 10:20 UTC by willirath

Closes #68

2022-08-11 12:11 UTC, willirath commented
Will continue here once #71 is solved.

2022-08-12 10:46 UTC, MarcoLandtHayen requested changes
Definition of NASSS index looks good. Since the index is standardized, it should have zero mean and unit variance. Please add a test for unit variance.

2022-08-12 11:26 UTC, willirath commented
@MarcoLandtHayen Test for standardisation is here: https://github.com/MarcoLandtHayen/climate_index_collection/blob/c61380633b7b27e894860e6c6c47722f574fcce0/tests/test_indices.py#L158_L170

2022-08-12 19:12 UTC, MarcoLandtHayen approved these changes

2022-08-12 19:12 UTC, merged